import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        <main className="h-screen w-full flex flex-col justify-center items-center p-4 text-7xl">
          {children}
        </main>

        <footer>
          <div className="w-full flex justify-center items-center border-t">
            <p className="text-gray-500">
              &copy; {new Date().getFullYear()} My Next.js App. All rights
              reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
